server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:

        jpa:
          show-sql: true
          hibernate:
            ddl-auto: update
          database-platform: org.hibernate.dialect.H2Dialect
      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
      feign:
        hystrix:
          enabled: true
      management:
        endpoints:
          web:
            exposure:
              include: "*"
