server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-224-64-114.compute-1.amazonaws.com:5432/d4nulhs3g22s9i
    username: heitdqciejmwkg
    password: 96ef287b5322e9a57a533ac849563877637eb9f0f60d2b88476a7362b0d55b34
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true 





