server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: